### PR TITLE
Implemented handling of inline queries

### PR DESCRIPTION
**Pull request by kartikluke**
For #7. I've implemented the handling of inline queries. But only for the roll command as of now. And it could probably use some refactoring.

### CODE REVIEW

**Comment by kartikluke** [comment]
@treetrnk Can you review this. I'm sure there's a lot to be improved. Just got it working for now.

**Comment by treetrnk** [comment]
I'm hoping to take a look at this soon. Thanks for the PR!

**Comment by kartikluke** [comment]
No problem. Been using this bot fairly regularly but often outside of my DnD group I'd like to roll for something without adding the bot.

I don't usually write Python so I assume it's a bit messy.

**Comment by treetrnk** [comment]
I was unable to get this pull request to work back when it was submitted. I didn't have a lot of time to work on it then though. Since then, I have updated the codebase to use python-telegram-bot. Feel free to submit another pull request to work with the new version and I'll take a look.

**Pull request closed without merging**
