### PR TITLE
Add explosion functionality

### PR DESCRIPTION
**Pull request by mattiadg**
I edited the regular expression in order to account for explosion.
Added explosion to the non-fate case, because I don't know if it's the same for fate dice.

### CODE REVIEW

**Comment by mattiadg** [comment]
It referes to Issue #12 Add handling of exploding dice using "!" in dice notation.

**Comment by mattiadg** [comment]
Ok, I've just noticed it's a bit more difficult than I expected, because there is an issue in message handling. I'm working at it.

**Comment by treetrnk** [comment]
It looks like this still doesn't actually implement exploding dice. I tried rolling `2d4!` several times and the 4s were never re-rolled.

**Comment by mattiadg** [comment]
I tried both 3d6! and stuff like 3d6!>4 and it worked. I will check later

Il 24/Ott/2016 03:45 AM, "Nathan Hare" <notifications@github.com> ha
scritto:

**Comment by treetrnk** [comment]
Okay. I'll have to take another look at it tonight.

**Comment by mattiadg** [comment]
That's what I get.
Isn't it correct?

2016-10-25 20:44 GMT+02:00 Nathan Hare <notifications@github.com>:

**Comment by treetrnk** [comment]
You are right. My mistake. I wasn't in the correct branch. Thanks for the help!

**Comment by mattiadg** [comment]
Ok nice!

Il 26/Ott/2016 03:06 AM, "Nathan Hare" <notifications@github.com> ha
scritto:

**Pull request merged**
